# SPDX-License-Identifier: GPL-3.0-or-later
# Compile current adapter methods against bounded native-boundary fixtures.
file(WRITE "${OUTPUT}" "// Generated from production adapter methods. Do not edit.\n")
function(extract_combat_method path signature)
    file(READ "${SOURCE_ROOT}/src/game/${path}" source)
    string(FIND "${source}" "${signature}" start)
    if(start LESS 0)
        message(FATAL_ERROR "Missing combat adapter method: ${signature}")
    endif()
    string(SUBSTRING "${source}" ${start} -1 body)
    string(FIND "${body}" "\n}" finish)
    if(finish LESS 0)
        message(FATAL_ERROR "Missing combat adapter boundary: ${signature}")
    endif()
    math(EXPR length "${finish} + 2")
    string(SUBSTRING "${body}" 0 ${length} body)
    file(APPEND "${OUTPUT}" "${body}\n")
endfunction()
extract_combat_method(Object/PlayerCoaCombat.cpp "void Unit::AdvanceCombatEpoch()")
extract_combat_method(Object/PlayerCoaCombat.cpp "bool Player::KnowsCoaCombatSpell(")
extract_combat_method(Object/PlayerCoaCombat.cpp "bool Player::IsCoaCombatAuthorized(")
extract_combat_method(Object/PlayerCoaCombat.cpp "void Player::SyncCoaCombatAuras()")
extract_combat_method(Object/PlayerCoaCombat.cpp "void Player::UpdateCoaCombatRules()")
extract_combat_method(Object/PlayerCoaCombat.cpp "bool Player::OnCoaCombatEvent(")
extract_combat_method(Object/PlayerCoaCombat.cpp "void CoaCombatTransaction::ReservePower(")
extract_combat_method(Object/PlayerCoaCombat.cpp "SpellCastResult CoaCombatTransaction::Prepare()")
extract_combat_method(Object/PlayerCoaCombat.cpp "bool CoaCombatTransaction::Publish()")
extract_combat_method(WorldHandlers/SpellAuras.cpp "void SpellAuraHolder::BuildUpdatePacket(")
get_filename_component(output_dir "${OUTPUT}" DIRECTORY)
set(OUTPUT "${output_dir}/CoaCombatGuidPacket.inc")
file(WRITE "${OUTPUT}" "// Native packed-GUID writer, outside fixture namespace.\n")
extract_combat_method(Object/ObjectGuid.cpp "ByteBuffer& operator<< (ByteBuffer& buf, PackedGuid const& guid)")
