# SPDX-License-Identifier: GPL-3.0-or-later
# Execute the current production methods against bounded fixture state, not copies.
file(WRITE "${OUTPUT}" "// Generated from current production source. Do not edit.\n")
function(extract_power_method path signature)
    file(READ "${SOURCE_ROOT}/src/game/${path}" source)
    string(FIND "${source}" "${signature}" start)
    if(start LESS 0)
        message(FATAL_ERROR "Missing power test method: ${signature}")
    endif()
    string(SUBSTRING "${source}" ${start} -1 body)
    string(FIND "${body}" "\n}" finish)
    if(finish LESS 0)
        message(FATAL_ERROR "Missing method boundary: ${signature}")
    endif()
    math(EXPR length "${finish} + 2")
    string(SUBSTRING "${body}" 0 ${length} body)
    file(APPEND "${OUTPUT}" "${body}\n")
endfunction()
extract_power_method(WorldHandlers/SpellChecks.cpp "uint32 Spell::CalculatePowerCost(")
extract_power_method(WorldHandlers/SpellChecks.cpp "SpellCastResult Spell::CheckPower()")
extract_power_method(WorldHandlers/SpellPower.cpp "void Spell::TakePower()")
extract_power_method(Object/SpellMgr.h "inline bool IsCasterSourceTarget(")
extract_power_method(Object/SpellMgr.h "inline bool IsSpellWithCasterSourceTargetsOnly(")
